# Travis CI configuration

language: node_js

node_js:
  - "9.0.0"

services:
  - docker

# Building docker image
before_install:
  - docker build -t clientresponse-demo .

# Verifying server.js for syntax errors, .js
# and .json files for style, using eslint
script:
  - node --check server/server.js
  - npm i -g eslint-plugin-json@1.2.0 eslint-plugin-react@7.9.1 eslint@4.19.1 babel-eslint@8.2.3
  - eslint --ext .json .js server client/src

cache:
  directories:
    - node_modules
